%% \VignetteIndexEntry{ChemmineOB Vignette}
% Manual compile
% Sweave("ChemmineOB.Rnw"); system("pdflatex ChemmineOB.tex; bibtex ChemmineOB; pdflatex ChemmineOB.tex; pdflatex ChemmineOB.tex")
% echo 'Sweave("ChemmineOB.Rnw")' | R --slave; echo 'Stangle("ChemmineOB.Rnw")' | R --slave; pdflatex ChemmineOB.tex;  bibtex ChemmineOB; pdflatex ChemmineOB.tex
\documentclass{article}

<<style, echo=FALSE, results=tex>>=
BiocStyle::latex()
@
\usepackage{hyperref}
\usepackage{url}
\usepackage{graphicx}
\bibliographystyle{plainnat}
\def\bibsection{\section{References}}

%\usepackage{a4wide}

\title{ChemmineOB}
\author{Kevin Horan \& Thomas Girke}



\begin{document}
\maketitle
\tableofcontents
\clearpage

<<echo=false>>=
	library(ChemmineOB)
@

\section{Introduction}
\Rpackage{ChemmineOB} provides an R interface to a subset of cheminformatics
functionalities implemented by the OpelBabel C++ project \citep{OBoyle2008a,
OBoyle2011a}. OpenBabel is an open source cheminformatics toolbox that includes
utilities for structure format interconversions, descriptor calculations,
compound similarity searching and more. \Rpackage{ChemineOB} aims to make a
subset of these utilities available from within R. For non-developers,
\Rpackage{ChemineOB} is primarily intended to be used from \Rpackage{ChemmineR}
\citep{Cao2008c, Backman2011a, Wang2013a} as an add-on package rather than used
directly. 

\section{Installation}
To use the \Rpackage{ChemmineOB} package on Linux or Mac, OpenBabel 2.3.0 or greater needs to
be installed on a system. On Linux systems, the header files are also required
to compile. The windows distribution will include its own version of OpenBabel.
The OpenBabel site (\url{http://openbabel.org/wiki/Get_Open_Babel}) provides excellent
instructions for installing the OpenBabel software on Mac or Linux
systems.  The \Rpackage{ChemmineR} and \Rpackage{ChemmineOB} packages can be
installed from within R with the \Rfunction{biocLite} install script.

If the installation fails on Linux, you may need to manually set the locations of the 
open babel libraries and header files. This is best done through configure flags. For
example, at the command prompt do:

\$ R CMD INSTALL  --configure-args='--with-openbabel-include=... --with-openbabel-lib=...' ChemmineOB

\noindent
where the '\ldots' are replaced by the relevant paths. See the README file for more details.

<<eval=FALSE, keep.source=TRUE>>=
source("http://bioconductor.org/biocLite.R") 
biocLite(c("ChemmineR", "ChemmineOB"))
library("ChemmineR")
library("ChemmineOB")
@

\section{User Manual in \Rpackage{ChemmineR} Vignette}
Detailed instructions for using \Rpackage{ChemmineOB} are provided in the
vignette of the \Rpackage{ChemmineR} package instead of this document.  The
main reason for consolidating the documentation in one central document rather
than distributing it across several vignettes is that it helps minimizing
duplications and inconsistencies. It also is the more suitable format for
providing a task-oriented description of functionalities for users. To obtain
an overview of the OpenBabel utilities supported by \Rpackage{ChemmineOB}, we
recommend consulting the \emph{OpenBabel Functions} section of the
\Rpackage{ChemmineR} vignette. To open the \Rpackage{ChemmineR} vignette from
R, one can use the following command.

<<eval=FALSE, keep.source=TRUE>>=
vignette("ChemmineR") 
@

\section{Version Information}
<<sessionInfo, results=tex, print=TRUE>>=
toLatex(sessionInfo())
@

\section{Funding}
This software was developed with funding from the National Science Foundation: \href{http://www.nsf.gov/awardsearch/showAward.do?AwardNumber=0957099}{{\textcolor{blue}{ABI-0957099}}}, 2010-0520325 and IGERT-0504249.

\bibliography{bibtex}

\end{document}
